### ISSUE TITLE
Use overflow: auto

### ISSUE THREAD

**Issue by Vluf** [Paol-imi/muuri-react#24] opened 2020-04-23 10:44 UTC
According to the docs, to use responsive styling, we need to use `overflow: scroll`:
https://paol-imi.github.io/muuri-react/docs/usage/responsive-style

Can this strict requirement be circumvented by recalculating the whole grid?
I've tried to use `overflow: auto` and using the grid reference to `.layout()` everytime an item is added (and would cause the scrollbar to suddenly appear). But that did not work.

Any other way to get `overflow: auto` to work? Having that scrollbar there all the whole time is not desirable for my use case.

**Comment by Paol-imi** [comment] 2020-04-23 10:57
The problem is not related to Muuri engine but to the CSS engine, so any workaround should be external.

The simplest approach that comes to mind is to force the size update by dispatching a fake resize event.

```js
onScrollbarVisibilityChange() {
    window.dispatchEvent(new Event('resize'));
}
```

The only case that comes to mind in which the scrollbar can appear / disappear is when items are added or change in size, so implementing this method in these cases should suffice.

If other approaches come to your mind you can share them here.

**Comment by Paol-imi** [comment] 2020-04-23 11:09
Muuri 0.8.0 ⚠️

There is a [**bug**](https://github.com/haltu/muuri/issues/372) in Muuri version 0.8.0 which will be fixed in the next release.
If you are calculating the style with the `getResponsiveLayout` utility it is possible that the dimensions are rounded upwards causing the layout to break.

For example if you use
```js
const style = getResponsiveLayout({
   columns: 1 / 2
})
```
It is possible that the dimensions are rounded up and Muuri inserts one item per row in the layout instead of two.

A quick workaround before 0.9.0 dies is released.

```js
const style = getResponsiveLayout({
   columns: 1 / 2 * .97 // Simply decrease the width.
})
```

**Comment by Vluf** [comment] 2020-04-23 11:26
The fake resize event did the trick! Perfect

**Closed** 2020-04-24 07:34 UTC
Labels: Related to Muuri 📦, enhancement 🛠, help wanted 👋

**Comment by Vluf** [comment] 2020-05-12 09:54
BTW: you need a workaround to dispatch a resize event on IE:
https://stackoverflow.com/questions/30571488/windows-resize-trigger-event-is-not-working-in-ie11
