### ISSUE TITLE
Library doesn't work (crashes) in newer versions of react

### ISSUE THREAD

**Issue by DoronTorangy** [paol-imi/muuri-react#49] opened 2021-01-16 15:30 UTC
This happens when running every example in the "showcase" pages using these versions:
muuri: 0.9.3
react: 17.0.1
react-dom: 17.0.1
muuri-react: 3.1.6 

![Untitled](https://user-images.githubusercontent.com/41499465/104815899-42eda380-5820-11eb-8849-02fc3d839b44.png)

**Comment by benbourgeois-92** [comment] 2021-04-10 15:57
Do we know what version it last ran at? I've run into this issue as well but downgrading didn't seem to have any effect.

**Comment by albiesoft** [comment] 2021-04-19 09:06
I have this issue with the latest of React and NextJS too

**Comment by ingcarlostello** [comment] 2021-05-09 22:42
**Im having the same issue with:**
    "muuri": "^0.8.0",
    "muuri-react": "^3.1.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.1",
![image](https://user-images.githubusercontent.com/48301281/117589180-afe9b980-b0ed-11eb-88f3-c9f4ee610862.png)

with this versions works fine:
    "muuri": "^0.9.3",
    "muuri-react": "^3.1.6",
    "react": "^16.14.0",
    "react-dom": "^16.13.1",

**Comment by alexandrsek** [comment] 2021-07-01 10:03
Any updates on this problem?

**Comment by christofflueck** [comment] 2021-07-19 08:16
Also would love for an update here. We really like the library but it blocks us from upgrading to react 17

**Comment by mrtijn** [comment] 2021-07-21 13:18
Created a quick fix:
https://github.com/mrtijn/muuri-react

`yarn add mrtijn/muuri-react#master`

Seems to working fine, tests are succeeding. 

Will try to create a PR here later.

**Comment by alexandrsek** [comment] 2021-07-29 16:52
> Created a quick fix:
> https://github.com/mrtijn/muuri-react
> 
> `yarn add mrtijn/muuri-react#master`
> 
> Seems to working fine, tests are succeeding.
> 
> Will try to create a PR here later.

I tried your fork with quick fix, everything worked pretty well until I wanted to add more items or remove some of them. So basically when children array changes Muuri Component doesn't update as intended.

For example, I have an array with 9 items. I add another item to array. Now children array contains 10 components, but MuuriComponent has only 9 Muuri Items. The new child is rendered, but styles are not applied and its not registered in Muuri grid.

I found a workaround for this by updating MuuriComponent key prop so it forces re-render, but it looks really bad with all that flickering and layout jumping.

Any ideas how to fix this?

Anyway, thank you for your help!

**Comment by marcelchastain** [comment] 2021-09-01 23:24
Opened a PR for this.
Ah @mrtijn just noticed you already found the same fix!
Oh well, glad it's working.

**Comment by mrtijn** [comment] 2021-09-03 11:52
Cool, forgot to create a PR 😅 Hope this can be merged soon!

**Comment by joernroeder** [comment] 2022-03-02 08:57
Hey, any progress on this issue. I patched my react 17 instance successfully via [patch-package](https://www.npmjs.com/package/patch-package) and the linked PR

**Comment by vingeraycn** [comment] 2022-04-26 06:31
Hello everyone, unfortunately muuri-react has not been updated for several years and there has been no community action, the muuri-react example no longer works on the latest version of React, so I have rebuilt a library muuri for react that does not depend on any version of React or muuri, depending on the version of your project depending on the version of

If you want to run muuri in React 17 or React 18, you can try this [library](https://github.com/vingeraycn/ruuri)

Happy coding!

**Comment by Hussainshaik579** [comment] 2022-09-27 11:06
![Screenshot from 2022-09-27 16-18-02](https://user-images.githubusercontent.com/77446245/192507322-304e9831-1e4b-4017-bb2a-226a75ac7ccc.png)

i'm having this issue when i start dragging. Sometimes it will create duplicate items

"muuri": "^0.9.3",
"muuri-react": "^3.1.6",
"react": "^16.8",
"react-dom": "^16.8",

**Closed** 2023-01-18 09:00 UTC

**Comment by Mohamed-Raid** [comment] 2023-09-13 09:06
same issue
