### ISSUE TITLE
onSend doesn't seem to be firing when trying to reparent.

### ISSUE THREAD

**Issue by Davenporten** [Paol-imi/muuri-react#16] opened 2020-04-03 19:28 UTC
I'm trying to reparent and the onSend doesn't seem to be firing. I have two MuuriComponents and have set everything up as per the tutorial (https://paol-imi.github.io/muuri-react/#/usage/reparenting) as seem below, but I must be missing something. 
```
export const layoutOptions = {
  dragReleaseDuration: 200,
  dragSortHeuristics: {
    sortInterval: 60
  },
  layoutDuration: 200,
  dragReleaseEasing: "ease",
  layoutEasing: "ease",
  dragEnabled: true,
  dragContainer: document.body,
  // The placeholder of an item that is being dragged.
  dragPlaceholder: {
    enabled: true,
    duration: 200,
    createElement: (item) => {
      return item.getElement().cloneNode();
    }
  },
};

const items = {

  target: [
    { id: "1", text: "Item 1", height: 1, width: 1, color: "blue" },
    { id: "2", text: "Item 2", height: 1, width: 1, color: "blue" },
    { id: "3", text: "Item 3", height: 2, width: 1, color: "blue" },
    { id: "4", text: "Item 4", height: 1, width: 1, color: "blue" },
    { id: "5", text: "Item 5", height: 1, width: 3, color: "blue" },
    { id: "6", text: "Item 6", height: 1, width: 1, color: "blue" },
    { id: "7", text: "Item 7", height: 1, width: 1, color: "blue" },
    { id: "8", text: "Item 8", height: 1, width: 2, color: "blue" },
    { id: "9", text: "Item 9", height: 2, width: 1, color: "blue" },
    { id: "10", text: "Item 10", height: 1, width: 1, color: "blue" },
    { id: "11", text: "Item 11", height: 1, width: 1, color: "blue" },
    { id: "12", text: "Item 12", height: 1, width: 1, color: "blue" },
  ],
  source: [
    { id: "13", text: "Extra", height: 1, width: 1, color: "blue" },
  ],
}

const MuuriTest = props => {

  const [cards, setCards] = useState(items);
  
  const targetChildren = cards.target.map(item => <DraggableCard key={item.id} {...item} />);
  const sourceChildren = cards.source.map(item => <DraggableCard key={item.id} {...item} />);
  return (
    <div>
      <MuuriComponent 
        {...layoutOptions} 
        dragEnabled
        id={"SOURCE"}
        onSend={({ key }) => {
          console.log('onSend source')
          // The sent item.
          const sentItem = cards.source.find(item => item.key === key)
          // The cards categories.
          const source = cards.source.filter(item => item !== sentItem)
          const target = cards.target.concat(sentItem)

          // Set the state.
          setCards({ source, target })
        }}
      >
        {sourceChildren}
      </MuuriComponent>
      <MuuriComponent 
        {...layoutOptions} 
        dragEnabled
        id={"TARGET"}
        onSend={({ key }) => {
          console.log('onSend target')
          // The sent item.
          const sentItem = cards.target.find(item => item.key === key)
          // The cards categories.
          const target = cards.target.filter(item => item !== sentItem)
          const source = cards.source.concat(sentItem)

          // Set the state.
          setCards({ source, target })
        }}
       >
        {targetChildren}
      </MuuriComponent>
    </div>
  );
};

export default MuuriTest;
```

The console.log() isn't even showing up. Any help on this would be much appreciated.

**Comment by Paol-imi** [comment] 2020-04-03 20:25
Hi Davenporten,

The fault is mine because I had little time to write the documentation and I left some holes. I am finishing version 3.1.0 of **muuri-react** where I will release new features and update the missing holes in the documentation.

What is missing is setting the [**dragSort**](https://paol-imi.github.io/muuri-react/#/muuricomponent/props?id=dragsort) and [**groupIds**](https://paol-imi.github.io/muuri-react/#/muuricomponent/props?id=groupids) props in the MuuriComponents.

```jsx
<MuuriComponent 
    // The MuuriComponent belongs to the group "Group-A".
    groupIds={["Group-A"]} 
    // The Items can be dragged only in MuuriComponent of the "Group-A".
    dragSort={{ groupId: "Group-A" }}
/>
```

Sorry for the inconvenience, the new release is practically ready and will be released together with Muuri 0.9.0. You can find the package on Github under the [**dev**](https://github.com/Paol-imi/muuri-react/tree/dev) branch.


### Problems

#### First

The component where onSend is triggered is the one that is receiving the item. 

#### Second

Looking at the code I see another potential problem, are you using useDrag in `<DraggableCard>`?

For now Muuri-react does [**not support**](https://paol-imi.github.io/muuri-react/#/hooks/useDrag?id=usage) the use of useDrag with reparenting, this problem will be solved in the next release.
<br><br>
Let me know if you can get your app to work or have other problems.

**Comment by Davenporten** [comment] 2020-04-03 21:44
I know how it goes with docs sometimes so no problem. Thanks so much for your quick response! I will follow your direction and see how things go. As for the useDrag problem I guess there is nothing I can do but wait for the next release. Thanks for all your help!

**Comment by Davenporten** [comment] 2020-04-06 12:08
@Paol-imi First, I'm sorry I didn't actually answer your question: yes, I am using useDrag in DraggableCard. That being said, I added what you suggested and the onSend callback still isn't firing. Is that because of the useDrag? Thanks again for all your help!

**Comment by tschneid** [comment] 2020-04-07 05:58
I'm experiencing the same issue.

For me `dragReleaseEnd` is never called for reparenting (this means, neither `onSend` is called, nor the low-level Muuri `grid.on('dragReleaseEnd' …)`.

**Comment by Paol-imi** [comment] 2020-04-07 08:05
Sorry if the problem lies between these design choices _(which can be discussed if you need to be expanded or modified)_ which are not yet in the online documentation _(Many improvements and new features will arrive in the new [**release**](https://github.com/Paol-imi/muuri-react/tree/dev))_.

- useGrid (the hook) is triggered every time the item is dragged over another grid and is inserted in it (in the instance of Muuri)
- onSend (should) be triggered when the item is released on another grid.

This is done to get the best performance and still be able to interact in any event.
Be careful that **dragReleaseEnd** is triggered on the grid from which the item was taken when the drag started, while **onSend** is triggered in the grid where the item was sent.

If the problem does not lie among them, it is perhaps possible that there is a problem within the reparenting process. Can you reproduce the case on codesandbox, perhaps starting from the [**kanban**](https://codesandbox.io/s/muuri-react-kanban-zmypd?file=/index.js) example where reparenting is active?

**Comment by tschneid** [comment] 2020-04-07 09:47
@Paol-imi I'm aware of that. Sorry for my brief unclear post.

I cannot reproduce this with v3.0.3 (which is also the version in the codesandbox). So with v3.0.3 reparenting works for me. I'm experiencing this issue in the `dev` branch (when I have `"muuri-react": "github:Paol-imi/muuri-react#dev"` in my `package.json`).

For the latest commit in `dev` I now also get other errors (independent of this issue, about passing `dragStartPredicate` amongst others), so I cannot test it right now. But for 123737c9 (latest commit in March) I can definitely tell that both `dragReleaseEnd` and `onSend` is not called when reparenting. Maybe @Davenporten can confirm this.

Is there a way to set up a condesandbox for the latest commit in `dev`? It doesn't seem like it works with gh references in the `package.json`.

**Comment by Paol-imi** [comment] 2020-04-07 10:43
I will do my best to release a stable version in the dev branch as soon as possible. 

This version will have quite a few changes and some tests will still have to be written, so it's to have problems. I don't always have much time to work on this project and this makes it difficult to have stable (dev) releases.

> when I have "muuri-reactions": "github: Paol-imi / muuri-reactions # dev" in my package.json

In recent commits I have changed some things regarding built packages, but this should give you the right package.

**Comment by Davenporten** [comment] 2020-04-07 11:38
> For the latest commit in dev I now also get other errors (independent of this issue, about passing dragStartPredicate amongst others), so I cannot test it right now. But for 123737c (latest commit in March) I can definitely tell that both dragReleaseEnd and onSend is not called when reparenting. Maybe @Davenporten can confirm this.

@tschneid I can confirm that `onSend` and `dragReleaseEnd` are not firing as specified.

**Comment by Paol-imi** [comment] 2020-04-09 18:46
I believe that in the next few days I will be able to release a stable dev version.

**Comment by tschneid** [comment] 2020-04-09 18:56
@Paol-imi Awesome! Let me know if I can help or test something.

**Comment by Paol-imi** [comment] 2020-04-09 19:11
Thank you very much for your help.
In the next release there will be a slight change in the reparenting algorithm to make it more efficient and with some small fixes. If it's a feature you use I would like to know if it causes you problems or is almost completely stable.

<br>

I took a look at consider.ly, and got an idea of ​​the use that will be made of muuri-react.

In the next version there will be new features that I think you may find interesting. If I can put the provisional dev documentation online (which I think is difficult in the short time I have), I will send you some links.

**Comment by Davenporten** [comment] 2020-04-10 10:53
> @Paol-imi Awesome! Let me know if I can help or test something.

Same here!

**Comment by Paol-imi** [comment] 2020-04-10 18:32
I have tried to release a stable version today as I will not be able to work on muuri-react in the next few days. I added some new tests and successfully tried the new version with some examples on codesanbox.
The tests to do are still many but I hope this version is stable and that you can use it.

Thanks for the help offered by both, now I will close this issue in favor of a more specific one where you can report any problems with the new dev version.

I'd like to know even if you can successfully implement what you were doing.

You can use the library with the command:

```bash
npm install muuri-react@dev
```

have a good weekend and happy easter.

**Closed** 2020-04-10 18:46 UTC
Labels: question 🤔

**Comment by Paol-imi** [comment] 2020-04-18 14:35
@Davenporten @tschneid 

The initial plan was to release the new version together with Muuri 0.9.0 as it already supports the new features. Since I don't think Muuri will be available soon, I decided to release the new version anyway as it brings several improvements.

The new documentation is online [**here**](https://paol-imi.github.io/muuri-react/).
