### ISSUE TITLE
Updating state with new items causes "Uncaught TypeError: Cannot read property '_component' of undefined"

### ISSUE THREAD

**Issue by kennyt6** [Paol-imi/muuri-react#4] opened 2020-01-30 20:32 UTC
![image](https://user-images.githubusercontent.com/59454837/73487707-63e18e00-435c-11ea-9302-a9b1857ed7b3.png)

After I initialize the grid with initial items, I try to update the muuri grid by updating the state of the items with new items. If I step through it I can see that the grid does get updated with the new items (although they are stacked on each other), somewhere down the line I get the errors above.

Searching around has suggested using 
`import * as React from 'react';`
but I already have that setup.

Any ideas on what could be going wrong?

**Comment by Paol-imi** [comment] 2020-01-30 21:08
It seems that the problem is related to the creation of the items.

If you could share a screenshot of your code or reproduce the error on codesandbox it would speed up the search for a solution.

Which version of muuri-react are you using?

**Comment by kennyt6** [comment] 2020-01-30 21:40
I'm using version 2.2.0. I'm a bit new to react so I hope its alright if I just paste my code here.
Here is the initial items and setItems
`
  const [items, setItems] = useState([
    {
      id: 1,
      name: 'test',
      sku_code: 'test',
      manufacturing: 'test',
      main_image: 'test',
      category: 'test',
      default_sell_price: '1',
    },
  ]);

  const children = items.map(item => (
    <Item
      key={item.id}
      id={item.id}
      name={item.name}
      manufacturing={item.manufacturing}
      main_image={item.main_image}
      category={item.category}
      sku_code={item.sku_code}
      default_sell_price={item.default_sell_price}
    />
  ));

const Item = ({
  id,
  name,
  sku_code,
  main_image,
  manufacturing,
  category,
  default_sell_price,
}: {
  id: any;
  name: string;
  sku_code: string;
  main_image: string;
  manufacturing: string;
  category: string;
  default_sell_price: string;
}) => {
  return (
    <div className="item">
      <div className="item-content">
        <ItemContainer>
          <FlexContainer>
            <LargeImageLink
              icon={<img src={StyleImage} />}
              headerText={`${name}`}
              text={`Style #${id} - $${default_sell_price}`}
              height={linkHeight}
              imagetype="gtest"
            />
          </FlexContainer>
        </ItemContainer>
      </div>
    </div>
  );
};
`

Here is the MuuriComponent
`<MuuriComponent
              options={{
                layoutDuration: 400,
                dragEnabled: false,
                height: 1000,
              }}
              onMount={onLayoutStart}
              ref={muuriRef}
            >
              {children}
            </MuuriComponent>`

It all works until I try to use this function to get the actual items from my backend.

`  const fetchStyles = async () => {
    try {
      await props.fetchClient
        .fetch(`/Styles`, {
          auth: true,
          method: 'post',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(filterRequest),
        })
        .then(resp => resp.json())
        .then(filterStyle => setItems(filterStyle.items));

    } catch (e) {
      throw new Error('server');
    }
  };
`

**Comment by kennyt6** [comment] 2020-01-30 21:44
I'm using version 2.2.0. 

![image](https://user-images.githubusercontent.com/59454837/73492820-4ca79e00-4366-11ea-9658-39c4897b30b3.png)

![image](https://user-images.githubusercontent.com/59454837/73492841-57fac980-4366-11ea-97e9-0ac534fbb59b.png)

Here is the MuuriComponent
![image](https://user-images.githubusercontent.com/59454837/73492873-6943d600-4366-11ea-8e00-e2253d6ce9fe.png)

It works fine loading the above, but when I update the state using the function below, it errors out. I've also tried this with just displaying the {id} in the item-content div but I got the same results.

![image](https://user-images.githubusercontent.com/59454837/73492926-8678a480-4366-11ea-9089-40a1e751a989.png)

Thanks for the quick response!

**Comment by Paol-imi** [comment] 2020-01-30 22:26
thanks for sharing, I think I have an idea where the problem may be.

Now I am working on new APIs that will be released in the next few days, the code has been modified where the problem may lie.

As soon as I have new updates I write here.

**Comment by Paol-imi** [comment] 2020-01-31 10:13
While I'm looking for any possible problems, you can try the new version (now in beta) which has had a great code-refactoring.
Maybe the problem doesn't appear with this version.

The beta should be stable, let me know if you have news.

```
npm install muuri-react@beta
```

**Comment by Paol-imi** [comment] 2020-03-05 16:01
The new 3.0.0 version of muuri-react is now published with all the documentation.
The main code has been changed and your problem should no longer exist. If you have other requests / problems contact me by opening an issue.

P.s.
If you are going to use this version for this project there is one thing you will need to change, now the options are used as props
```js
<MuuriComponent
  layoutDuration={400}
  dragEnabled={false}
  onMount={onLayoutStart}
  ref={muuriRef}
>
   {children}
</MuuriComponent>
```

**Closed by Paol-imi** 2020-03-05 16:01 UTC

**Comment by mrtijn** [comment] 2020-04-24 10:35
I encountered this problem too. It has to do with the keys not being unique. 
But instead of throwing a fancy error, it crashes with the error above .

**Comment by kennyt6** [comment] 2020-04-25 19:31
I ended up going with another grid system. Thanks anyways!
